#!/usr/bin/env bun
/** Generate the readable CLI reference from the Commander command tree. */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { buildProgram } from "../src/cli/main.ts";
import { defaultSpawn, PROCESS_STDIO } from "../src/cli/output.ts";

const OUTPUT = resolve(import.meta.dir, "../docs/cli-reference.md");

function render(): string {
	const program = buildProgram({ env: {}, stdio: PROCESS_STDIO, spawn: defaultSpawn });
	const sections: string[] = [
		"<!-- AUTO-GENERATED by `bun run gen:cli-reference` from `src/cli/main.ts`. -->",
		"<!-- Do not edit by hand; run `bun run gen:cli-reference`. -->",
		"",
		"# Warren CLI reference",
		"",
		"This reference is generated from the Commander command tree so command names, arguments, options, and descriptions stay aligned with the executable CLI.",
		"",
	];

	const visit = (command: typeof program, parents: string[] = []): void => {
		const path = [...parents, command.name()].join(" ");
		sections.push(`## ${path}`, "", "```text", command.helpInformation().trimEnd(), "```", "");
		for (const child of command.commands) visit(child, [...parents, command.name()]);
	};
	visit(program);
	return `${sections.join("\n").trimEnd()}\n`;
}

const generated = render();
const check = process.argv.includes("--check");
let current: string | null = null;
try {
	current = readFileSync(OUTPUT, "utf8");
} catch {
	// Missing output is handled by the comparison below.
}
if (check) {
	if (current !== generated) {
		console.error("docs/cli-reference.md is missing or stale. Run `bun run gen:cli-reference`.");
		process.exit(1);
	}
	console.log("gen:cli-reference ok");
} else {
	writeFileSync(OUTPUT, generated);
	console.log(`generated ${OUTPUT}`);
}
